authorName: default
experimentName: helixer_test
trialConcurrency: 2
maxTrialNum: 10000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_danq.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, BOHB
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: /home/felix/git/HelixerPrep/helixerprep/prediction/DanQModel.py -v -d ~/Desktop/data/nine_genomes/h5_data_10k --nni --gpus 2 -bs 128 -e 2
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
